# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  (1..2).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "generic/ubuntu2004" 
      node.vm.hostname = "node#{i}"

      node.vm.provider :libvirt do |libvirt|
        libvirt.memory = i == 1 ? "2048" : "1024"
        libvirt.cpus = i == 1 ? 2 : 1
      end

      node.vm.provision "shell", path: "bootstrap.sh"
    end
  end

  config.trigger.after :up do |trigger|
    trigger.name = "Getting the IP address of the VMs"
    trigger.ruby do 
      File.open("ip_address.txt", "w") do |f|
        (1..2).each do |i|
          ip = %x(vagrant ssh node#{i} -c "hostname -I | awk '{print $1} '").strip
          f.write("#{ip}\n")
        end
      end
    end
  end
end