---
# tasks for master nodes

- name: Set hostname
  ansible.builtin.hostname:
    name: "controlplane"


- name: Check if Kubernetes /etc/kubernetes/admin.conf file exists
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: admin_conf_stat

- name: Initialize Kubernetes cluster
  ansible.builtin.command:
    cmd: kubeadm init
  register: kubeadm_output
  changed_when: false
  when: admin_conf_stat.stat.exists == false

- name: Ensure ~/.kube directory exists
  ansible.builtin.file:
    path: "~/.kube"
    state: directory
    mode: "0755"
  become_user: "{{ ansible_user }}"

- name: Copy /etc/kubernetes/admin.conf to ~/.kube/config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
  become: true
  
- name: Set permissions on ~/.kube/config
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube/config"
    mode: '0755'
  become: true

- name: Copy /etc/kubernetes/admin.conf to ./config
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "./config"
    flat: yes


- name: Apply Calico CNI network plugin
  ansible.builtin.command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
  become: false
  when: admin_conf_stat.stat.exists == false

- name: Store join command output to file
  ansible.builtin.copy:
    content: "{{ kubeadm_output }}"
    dest: ./kubeadm_join_command.log
    mode: '0755'
  delegate_to: localhost
  become: false
  when: admin_conf_stat.stat.exists == false

- name: Run kubeadm token command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: kubeadm_token_output

- name: Store kubeadm token output to file
  ansible.builtin.copy:
    content: "{{ kubeadm_token_output.stdout }}"
    dest: "./kubeadm_token_command"
    mode: '0755'
  delegate_to: localhost
  become: false
